When building with clang, disable -Wunneeded-internal-declaration for several sys/cam/ctl files, since these get the following warnings:
In file included from sys/cam/ctl/ctl_backend.c:60:
sys/cam/ctl/ctl_private.h:300:30: error: variable 'page_index_template' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
static struct ctl_page_index page_index_template[] = {
                             ^

These warnings are tricky to fix without a lot of overhaul, and they are
harmless, so disable them for now.

MFC after:	1 week


git-svn-id: svn+ssh://svn.freebsd.org/base/head@231978 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f